#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link      http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license   http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
defined('SYSTEM_NAME') || define('SYSTEM_NAME', 'questionnaire-api');

require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';
require dirname(__FILE__) . '/../app/config/mode.php';

$config = require __DIR__ . '/../app/config/' . APPLICATION_ENV . '/console.php';

if (isset($config['params']['sub_database']) && $config['params']['sub_database'] == true) {
    $args = $argv;
    run_by_brand($config, $args);
} else {
    (new yii\console\Application($config))->run();
}